# Generated by Django 5.1.1 on 2024-09-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_producttinychef_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttinychef',
            old_name='app_name',
            new_name='name',
        ),
    ]
